### Numpy
Numpy is a fundamrntal library for scientific computing in pyhton. It provides support for arrays and matrices, along with a mathematical functions to operate on these data structure. 
Basics of Numpy, arrays and vectorized operations....

In [4]:
# creating a 1D array with numpy
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5) # reshaping the array to 1 row and 5 columns


array([[1, 2, 3, 4, 5]])

In [10]:
arr2=np.array([[1, 2, 3, 4, 5], [9, 8 ,7, 6, 5]]) # creating a 2D array
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [9 8 7 6 5]]


(2, 5)

In [12]:
np.arange(0,10,2).reshape(5,1) # creating an array with values from 0 to 10 with a step of 2 and reshaping it to 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4)) # creating a 3x4 array filled with ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# Identity matrix
np.eye(3) # creating a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of mnumpy
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape: ", arr.shape)
print("Number of dimentions: ", arr.ndim)
print("size (number of elemenets): ", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimentions:  2
size (number of elemenets):  6
Data type: int64
Item size (in bytes):  8


In [17]:
# NUmpy vectorize operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Element wise addition
print("Addition : ", arr1 + arr2)

# Element wise subtraction
print("Subtraction : ", arr1 - arr2)

# Element wise multiplication
print("Multiplication : ", arr1 * arr2)

# Element wise division
print("Division : ", arr1 / arr2)

Addition :  [ 7  9 11 13 15]
Subtraction :  [-5 -5 -5 -5 -5]
Multiplication :  [ 6 14 24 36 50]
Division :  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [18]:
# Universal functions
arr = np.array([1, 2, 3, 4, 5])
# Square root of each element
print(np.sqrt)

# Exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# logarithm
print(np.log(arr))

<ufunc 'sqrt'>
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [19]:
# array slicing and indexing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Aarray: \n", arr)

Aarray: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr[0, 1]  # Accessing the element at row 0, column 1

np.int64(2)

In [26]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [30]:
arr[1:,2:]

array([[6],
       [9]])

In [5]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
arr1[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [10]:
arr1[1:2:3]

array([[5, 6, 7, 8]])

In [12]:
print(arr1[0][0])
print(arr1[0:2,1:])

1
[[2 3 4]
 [6 7 8]]


In [14]:
print(arr1[1:,1:3])

[[ 6  7]
 [10 11]]


In [17]:
# Modify array elements
arr1[0,0] = 100
print(arr1)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [18]:
arr1[1:] = 100
print(arr1)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [19]:
# Statistical concepts nof normalization
# to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data : ", normalized_data)



Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [20]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8 , 9, 10])

# Mean
mean = np.mean(data)
print("Mean : ", mean)

# Median
median = np.median(data)
print("Median : ", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation : ",std_dev)

# Varience
varience = np.var(data)
print("Varience : ", varience)

Mean :  5.5
Median :  5.5
Standard Deviation :  2.8722813232690143
Varience :  8.25


In [23]:
# Logical Operation
data = np.array([1, 2, 3, 4 ,5, 6, 7, 8, 9, 10])
data[data>5]

array([ 6,  7,  8,  9, 10])

In [24]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])